run:
  timeout: 5m
linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - gofmt
    - goimports
    - misspell
output:
  format: tab
  print-issued-lines: true
  print-linter-name: true
